# Site settings
title: Comoc IM
SEOTitle: Comoc IM
description: "Comoc IM - communicate at ease."
keyword: "Free IM, Comoc, chat"
url: "http://comoc-im.github.io"
github_repo: "https://github.com/comoc-im/web.git"
