name: Comoc web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i -g yarn
    - run: yarn install
    - run: yarn run build
      # create a copy of index.html
    - run: cp ./dist/index.html ./dist/404.html
    - name: GitHub Pages action
      # You may pin to the exact commit or the version.
      # uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        # Set a SSH private key from repository secret value for pushing to the remote branch.
        #deploy_key: # optional
        # Set a generated GITHUB_TOKEN for pushing to the remote branch.
        github_token: ${{ secrets.GITHUB_TOKEN }} # optional
        # Set a personal access token for pushing to the remote branch.
        #personal_token: # optional
        # Set a target branch for deployment.
        #publish_branch: # optional, default is gh-pages
        # Set an input directory for deployment.
        publish_dir: ./dist # optional, default is public
        # Set an destination subdirectory for deployment.
        #destination_dir: # optional, default is
        # Set an external repository (owner/repo).
        #external_repository: # optional
        # If empty commits should be made to the publication branch
        #allow_empty_commit: # optional, default is false
        # If existing files in the publish branch should be not removed before deploying
        #keep_files: # optional, default is false
        # Keep only the latest commit on a GitHub Pages branch
        #force_orphan: # optional, default is false
        # Set Git user.name
        #user_name: # optional
        # Set Git user.email
        #user_email: # optional
        # Set a custom commit message with a triggered commit hash
        #commit_message: # optional
        # Set a custom full commit message without a triggered commit hash
        #full_commit_message: # optional
        # Set tag name
        #tag_name: # optional
        # Set tag message
        #tag_message: # optional
        # Enable the GitHub Pages built-in Jekyll
        #enable_jekyll: # optional, default is false
        # An alias for enable_jekyll to disable adding .nojekyll file to master or gh-pages branches
        #disable_nojekyll: # optional, default is false
        # Set custom domain
        cname: comoc.chummy.fun # optional
        # Set files or directories to exclude from a publish directory.
        #exclude_assets: # optional, default is .github
