name: Comoc web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i -g yarn
    - run: yarn install
    - run: yarn run build
    - name: GitHub Pages Overwriter
      # You may pin to the exact commit or the version.
      # uses: rayluo/github-pages-overwriter@b680c94786ac08c0e865b1b8a79a562231e582e4
      uses: rayluo/github-pages-overwriter@v1.2
      with:
        # The name of the source directory that you wish it to become the wwwroot of your website
        source-directory: dist # optional, default is .
        # The name of the branch that would be OVERWRITTEN by current workdir, you will then configure your Github Pages to serve this branch.
        target-branch: gh-pages # optional, default is gh-pages
